### ISSUE TITLE
Graph in list of graphs does not exist

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#129]
I have a graph listed in the group TFregression: [core-network-edgethreshold-5e-02](http://graphspace.org/graphs/ategge@vt.edu/core-network-edgethreshold-5e-02). This graph used to exist. When I click on the link for this graph, I see the error message: 

> Graph: core-network-edgethreshold-5e-02 does not exist for ategge@vt.edu. Upload a graph with this name into GraphSpace in order to see it.

If I try to delete this graph, I see the following popup box:

> No Such Graph Exists.

I believe this is happening because I stopped updating the graph halfway through the update process. However, I should not have a graph listed in my list of graphs if it does not exist.

**Comment by DSin52** [comment]
Interesting.. there is no graph in the graph table, however, since you didn't explicitly delete the graph.. there is still a reference to this since it is still shared with the group.  I will remove this graph from the group. I am not really sure how to automatically handle this case in the future though..

**Comment by tmmurali** [comment]
Allison, how did you stop updating the graph halfway through the update
process? Did you kill a programme?

**Comment by ategge** [comment]
Murali, Yes, I killed the program since it was taking so long to upload.
