### ISSUE TITLE
Tags with ";" character are broken

### ISSUE THREAD

**Issue by xin30hp** [Murali-group/GraphSpace#157]
I have graphs with the tag "ErbB2;erbB2_receptor" and when I click on it the tag to see the collection of graphs with that tag, I get "It appears that you currently have no graphs uploaded that match the tag terms." and has the tag show as only "ErbB2" in the search terms.  I think its getting split with a ";" delimiter when all the tags themselves should be strings?

**Comment by tmmurali** [comment]
@xin30hp, for now just change the tag to something like "Erb2-erbB2_receptor".

**Comment by adbharadwaj** [comment]
@xin30hp Ideally if a user wants to add multiple tags they should provide multiple tags for the graphs instead of providing a string separated by semi-colon. In GraphSpace 2.0, since semi-colon is a special character,"ErbB2;erbB2_receptor" will be split into multiple tokens. Therefore the search query will be equivalent to "tags:ErbB2" AND "tags:erbB2_receptor"
