### ISSUE TITLE
Error after a fresh install

### ISSUE THREAD

**Issue by MridulS** [Murali-group/GraphSpace#186]
I cloned the repo and went through the steps in the readme for a fresh install.
`python manage.py runserver` executed without any problem.
But when I tried to create a new user account through the browser I got this message.
``` 
 File "/usr/local/lib/python2.7/dist-packages/bcrypt/__init__.py", line 50, in gensalt
    output = _bcrypt.ffi.new("unsigned char[]", 30)
AttributeError: 'module' object has no attribute 'ffi'
```

@DSin52 @adbharadwaj Any clue?

**Comment by adbharadwaj** [comment]
I think it's because of some package version conflict.

I solved it by creating a virtual environment for the application. Take a
look at virtualenv package.

Hope it helps.

*Aditya Bharadwaj*
Graduate Research Assistant,
Department of Computer Science,
Virginia Tech
adb@vt.edu

I cloned the repo and went through the steps in the readme for a fresh
install.
python manage.py runserver executed without any problem.
But when I tried to create a new user account through the browser I got
this message.

 File "/usr/local/lib/python2.7/dist-packages/bcrypt/__init__.py",
line 50, in gensalt
    output = _bcrypt.ffi.new("unsigned char[]", 30)
AttributeError: 'module' object has no attribute 'ffi'

@DSin52 <https://github.com/DSin52> @adbharadwaj
<https://github.com/adbharadwaj> Any clue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Murali-group/GraphSpace/issues/186>, or mute the thread

**Comment by tmmurali** [comment]
@adbharadwaj Your solution will not work for anyone who follows the instructions we currently have on GitHub for installing GraphSpace. Can either you or @MridulS dig in and find out what have replaced the ffi function/variable in newer versions?

Does https://github.com/SimonSapin/cairocffi/issues/62 shed any light? Please discuss in this thread before committing a fix.

**Comment by adbharadwaj** [comment]
I am not sure which package is causing a conflict. This is a common problem
and is usually handled using well required packages file with compatible
versions

But I have already implemented the standard installation solution for
Graphspace. This solution fixes two things - python dependency management
and settings management for multiple environment.

I am talking about the first two commits in this branch.
https://github.com/Murali-group/GraphSpace/commits/%23176

Once I have made changes to the readme document, I will send a pull request
to the master branch.



*Aditya Bharadwaj*
Graduate Research Assistant,
Department of Computer Science,
Virginia Tech
adb@vt.edu

**Comment by adbharadwaj** [comment]
About  SimonSapin/cairocffi#62
<https://github.com/SimonSapin/cairocffi/issues/62> , I did try this to no
success.

*Aditya Bharadwaj*
Graduate Research Assistant,
Department of Computer Science,
Virginia Tech
adb@vt.edu

**Comment by tmmurali** [comment]
OK. These changes are very good. @adbharadwaj Let me know when you change the README so that I can review it.

**Comment by tmmurali** [comment]
@adbharadwaj @MridulS Can we close this issue now?

**Comment by adbharadwaj** [comment]
@MridulS <https://github.com/MridulS> can you close this issue since you
opened it.

*Aditya Bharadwaj*
Graduate Research Assistant,
Department of Computer Science,
Virginia Tech
adb@vt.edu

**Comment by MridulS** [comment]
Yeah, it is fixed now.

@adbharadwaj Thanks :)
