### ISSUE TITLE
No local packages or download links found for SQLAlchemy==1.0.14* even after installing sqlalchemy

### ISSUE THREAD

**Issue by philosopherstoneguy** [Murali-group/GraphSpace#201]
Searching for SQLAlchemy==1.0.14*
Reading https://pypi.python.org/simple/SQLAlchemy/
Download error on https://pypi.python.org/simple/SQLAlchemy/: Tunnel connection failed: 407 Proxy Authentication Required -- Some packages may not be found!
Couldn't find index page for 'SQLAlchemy' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: Tunnel connection failed: 407 Proxy Authentication Required -- Some packages may not be found!
No local packages or download links found for SQLAlchemy==1.0.14*
error: Could not find suitable distribution for Requirement.parse('SQLAlchemy==1.0.14*')
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

I am getting this error whenever i try to run install.sh. I have already installed all the requirements for GraphSpace even after that I am getting this error I even try to install them after  running ''source venv/bin/activate'.
here a screentshot
![screenshot from 2016-09-06 16 18 19](https://cloud.githubusercontent.com/assets/20800446/18271096/fe2f2d8c-744d-11e6-8626-bf1757196bb8.png)

**Comment by adbharadwaj** [comment]
`pip` has issues working behind the proxy. I believe you are living in a hostel, hence the proxy issue. There is no well-defined way of handling this issue. Here are some links which may help:

- http://stackoverflow.com/questions/14149422/using-pip-behind-a-proxy
- https://github.com/pypa/pip/issues/1182

If these links do not help, I suggest you do the following after running `source venv/bin/activate`:

1. Download each package in `requirements.txt` file.
2. unzip it if it is zipped.
3. cd into the directory containing setup.py
4. If there are any installation instructions contained in documentation contained herein, read and follow the instructions OTHERWISE
5. type in `python setup.py install`

Incase, you do noty have sudo access use `python setup.py install --user`.

**Comment by philosopherstoneguy** [comment]
pip is working fine I already used required commands to  work behind the proxy and i installed these required packages  after the running the source venv/bin/activate command

**Comment by adbharadwaj** [comment]
May be !! Can you run pip install command for each required package and start working for now. We can resolve this issue later.
