### ISSUE TITLE
 Allow users to fork/clone a graph.

### ISSUE THREAD

**Issue by adbharadwaj** [Murali-group/GraphSpace#336]
Add a fork button to allow a user to make a copy of a graph.

**Comment by tmmurali** [comment]
@adbharadwaj Isn't this a part of the "Git for Graphs" project we are proposing for 2018 GSoC? Implementing cloning/forking might require thinking about all the requirements for "Git for Graphs".

**Comment by adbharadwaj** [comment]
@tmmurali it is but I added this issue as good exercise for anyone trying to apply for `Git for graphs` project. Aim is to build a proof of concept functionality. Conceptually, its a easy implementation. All we have to do is fetch the graph json and style son for a graph and clone by uploading them for the current user.

**Comment by tmmurali** [comment]
OK. Makes sense.

**Comment by jahandaniyal** [comment]
Hi Mentors,

I would love to work on the **"Git for graphs"** project as a part of **2018 GSOC**. 
In order to familiarize myself with the source code of **Graphspace** I will try my hands on some of the 'good first issues'. I'm in the process of completing the local setup (currently on a windows 10 surface tablet - though I will be working mostly on Ubuntu ). I have read few sections of the **Graphspace** usage manual and I believe it should be sufficient to tackle the 'good first issues'. 
I saw a suggestion by one of the Mentors to improve the README.MD documentation. If you want, I can add a separate section listing the steps to build on Windows. Perhaps add download links of requirements as well. 

**Some details about myself** 
I'm currently pursuing Master of Computer Science at the Technical University of Berlin (TU Berlin). 
I have about 2 years of experience working as a Full-Stack Web Developer.
Technology stack of the project  - 
Django, Python, Bootstrap, JQuery, Knockout.js, PostgreSQL, jqplot (and few other graphical library).

In 2013, while pursuing Bachelor's of Technology, I made a simple Graph visualization application using Java-Swing. It creates a graphical representation of un-directed acyclic graphs (input is a datafile) and it allows the user to interactively find the shortest path between two nodes. It was a very small hobby project and in no way does it compare with Graphspace. I thought it was worth mentioning, as this is the reason why I'm so interested in this project.

**Comment by adbharadwaj** [comment]
Hi Daniyal,

Any kind of contribution to README.md will be helpful. Thanks.

Although for the GSoC project we would be evaluating on the basis of the
patch submitted for one of the Github issues. I would recommend you to take
up this issue if feasible.

https://github.com/Murali-group/GraphSpace/issues/336

*Aditya Bharadwaj*
Graduate Research Assistant,
Department of Computer Science,
Virginia Tech
adb@vt.edu

**Comment by jahandaniyal** [comment]
I have implemented the following features for a proof of concept - **Fork** functionality :
1. User can fork any public/shared graph. Anonymous Users cannot fork.
2. The forked graph gets added to **My Graphs** list of the current user. Visibility is set using the **is_public** variable.
3. The **owner_email** field is overwritten **uid** of the current user i.e the email ID of the user who forked the graph. 
3. Fork button is only visible for graphs the user doesn't own or hasn't forked previously. 

There are few features I would like to implement but it may require changes to the Graph data structure. Hence, I'm asking the mentors for suggestion.

I thought about few things which may be desirable for the Fork functionality -
a) Ideally, We want to maintain a link between the forked graph and the parent one. We could maintain a link (analogy of a linked list) to the parent graph, perhaps, by adding **forked_id** field (for example) to the graph data structure. This would allow us to maintain a hierarchical structure.  The current implementation creates a copy of a graph, and once forking is complete all information about the parent graph is lost. Currently, there's no way of knowing whether the graph was forked or uploaded by the user. 
For the purpose of testing the functionality I have set **is_public** variable to correspond to Private visibility. 
b) If we can store information about the parent graph, then instead of displaying 'Already forked' - we could give a clickable link to the parent graph. Something like forked from **< Parent Graph Name >** .  


![fork_demo](https://user-images.githubusercontent.com/4581090/35816252-8ef0c158-0a9a-11e8-82bf-20e66fd51784.gif)

**Comment by tmmurali** [comment]
@jahandaniyal This is an excellent start! You have added very useful functionality. The points you are raising about additional features are very valid. 

Maintaining a link to the parent graph is essential. So that seems to be critical functionality to implement, especially after a bit more thought and design. It will require change to the PostgreSQL database, unless we can figure out how to keep this information in the Elasticsearch database.

I am also concerned about what happens if I fork graph A to graph B but then A's owner changes A itself. This issue may rear its head especially when we allow a user to fork any graph shared with them. 

My instinct is to keep the forked graph as private.

**Comment by jahandaniyal** [comment]
prof. @tmmurali I have kept ownership of the forked graph to Private by default. 


For maintaining link to the parent graph, we could take advantage of the fact that each graph is referenced by an unique graph_id in the database. Based on this reasoning, I have thought of 2 possible options which might fit the requirement :
1. Add an extra field to Graph data structure.
This would require making changes to the database. 
The current Graph stores the following information as key, value pairs in a dictionary :
**Graph(K, V) -> { 'name' :' ', 'owner_email', ' ', 'is_public': ' ', 'graph_json' : ' ', 'style_json': ' '}**
we could add another key-value pair like **{'parent_id' : ' '}** and any other detail as may be needed.
2. This method requires no changes to the database itself, but might impact the current functionalities. 
We can store information about the parent graph in graph METADATA - like the **'graph_json'** field. **graph_json** has an entry for 'data' where it stores information about the description, name, and tags of the graph. We could create key-value pairs like **{'parent_id' : ' ',  'parents_email' : ' ' }** and append it to data. 

Regarding the scenario you pointed out, **B < forked from > A**, then changes are made to **A**. At this moment, I'm not completely certain of the best way to tackle this problem. 
I look forward to your suggestions.

**Comment by jahandaniyal** [comment]
@tmmurali @adbharadwaj 
I have tried to implement link to the parent graph, similar to the behaviour we have in Github.
I would like to demonstrate the following scenarios :
1. A user opens a graph he had uploaded himself. 
**Observation -** UI has no **Fork Button** or **forked from message**.
2. User opens a graph he had forked earlier. 
**Observation -** forked from **parent_graph_owner's_email / Name of graph** is displayed. The user can click on this link to go to the parent graph. Similar to what he have on Github.
3. User opens the Parent Graph which he already forked and tries to **Fork** again. 
**Observation -** A message is displayed stating that the user has already forked the graph. 
Github on the other hand, redirects to the existing fork instead of showing any message.
I can implement similar behaviour for Graphspace if desired.
4. User shares a graph to public and tries to fork it himself. 
**Observation -** Same as case 1.

A general scenario would be that User A uploads a graph and shares it to public. User B can then fork the graph as described in the above cases. 

![fork_demo2](https://user-images.githubusercontent.com/4581090/36041612-5cfbb400-0dc9-11e8-9442-f6762907da30.gif)


Regarding the issue that parent graph might change later on - we can give notification to the users whenever they open the forked graph. Can we use the existing notification framework for sending the notification?. Please give your suggestions.

**Comment by adbharadwaj** [comment]
@jahandaniyal I like the demo. It showcases all of the basic use cases required for fork/clone functionalities. I think this is a good POC for Git `Diff` project. 

Here is what I think of the two options suggested by @jahandaniyal.

1. First option will require a db change. The problem is that most of the time the column will be empty and would refer to any graph which will be a waste of space. 

2. Second option will require no change in the PostgreSQL database schema. We just have to add a special field in graph_json. I would prefer this option.

Ideally here is how I would handle the following cases:

1. **Parent graph is updated**  - In such a case I wouldn't wanna take any action on the child graph just like GitHub. But user would wanna see the difference between his/her forked graph and parent graph using some kind of `Diff` tool.

2. **Parent graph is deleted** - In such case, we continue to keep the parent reference. But when a user clicks on Parent graph hyperlink, they should see a message that the parent graph has been deleted.

3. **Child graph is updated** - Again, user might wanna see the difference between parent and current graph.

**Comment by jahandaniyal** [comment]
For the POC demonstration I have used the 2nd method. So, the entry for 'data' now has 'description', 'tags', 'names', and 2 other fields.
I will implement the changes @adbharadwaj  mentioned above. I would also like to work on the **Git diff** POC if it's available. 
May I commit the changes I've done so far? Or should I commit to my forked repository for the time being.

**Comment by adbharadwaj** [comment]
You don't have to implement the Diff feature. It's a separate feature and part of a different project.

You can send a pull request with the changes. The aim of this issue is to just allow users to clone graph.

**Comment by tmmurali** [comment]
I have been thinking about how to refer to the parent graph from the forked graph. Adding a field to the JSON of the forked graph seems to be ripe for misuse. 

A user could add this field to their graph's JSON and make it appear that it is forked from some other graph when it is truly is not. It might also happen due to a mistake in a script. 

GraphSpace must record the fork in its database to prevent these types of errors or misuse.

**Comment by adbharadwaj** [comment]
@tmmurali  That's a valid concern. 

@jahandaniyal Can you come up with a plan to handle this issue using Option 1 (adding a parent column)? I want to make sure that you understand how to make this change before implementing it.

**Comment by jahandaniyal** [comment]
For reading the graph description I would like to suggest using the existing REST api to fetch graph (id=<parent_id>) and then filter the data, since we only want the graph description and not the json data for parent.  Or, I can create another endpoint for fetching only the graph description?

**Comment by adbharadwaj** [comment]
@jahandaniyal I didn't really understand when will the `ParentGraphAlreadyExists` error be raised? 

We cannot use a default value of 0 because 0 will mean that parent exists. We will have to use NULL as default. 

I don't we need to make changes to `GET graphs` REST api.

**Comment by jahandaniyal** [comment]
@adbharadwaj Thanks for clearing my doubts. Regarding `ParentGraphAlreadyExists `, I was thinking of adding an extra layer of check in the server-side itself for the case when User tries to fork any graph more than once. In the current implementation we are handling this case in the UI itself.

**Comment by tmmurali** [comment]
@jahandaniyal @adbharadwaj are we allowing forking/cloning through the REST API?

**Comment by jahandaniyal** [comment]
@tmmurali We will be using the existing ` POST Graph` API for forking. We could have added a new API only for forking but too many APIs doing similar tasks will only increase redundancy in the source code.

**Comment by tmmurali** [comment]
Thanks. What is the syntax for the fork command?

**Comment by jahandaniyal** [comment]
The syntax will be like `POST graphs` - http://www.graphspace.org/static/api.html#graphs_post. 
A Javascript example would be similar to  `apis.graphs.add( data, successCallback(), errorCallback())`. Where `data` is `{'keys':'values'}` consisting of the graph's data.
Another aspect that i'm considering is whether to allow user to fork graph by only specifying the `graph_id`. The existing `POST graphs` API however requires graph data to be passed with the request.
@adbharadwaj could you please clarify on the REST API use cases :
1. `POST `specifying graph data (this could be the case when a user made some changes to a graph using UI and wants to fork the current state).
2. `POST` specifying only graph_id (graph is then fetched from the database and forked). This will be very helpful for someone building external application on top of Graphspace.

**Comment by tmmurali** [comment]
The forking user must specify the id of the original graph, otherwise how will GraphSpace record that it is a fork.

Overloading post functionality seems to be bad design. We need to be more explicit about it being 
a fork operation. @adbharadwaj can you comment?

**Comment by jahandaniyal** [comment]
Prof. @tmmurali I agree that it is a bad idea to mess around with existing REST APIs. . 
But we are adding a new field(`parent_graph_id`) to the graph table in the database. Now, when a user forks a graph we need to create a new graph for that user with the `parent_id=<value>` field set and to create a new Graph we already have the existing `POST graph` API. The current POST conditionally handles the case when no `style_json` is specified, I was thinking along the same line for fork. Perhaps, I might have misinterpreted the requirements. 
For case 1: Sorry, I wanted to imply that user can pass parent_id with the graph data itself as the current `POST graph` doesn't pass the graph_id implicitly. But this won't be necessary if we are to explicitly handle fork operation by a separate API ENDPOINT. 
Using a new ENDPOINT like `POST graphs/{id}/fork` will solve the issue. @adbharadwaj can clarify on this.

**Comment by adbharadwaj** [comment]
@jahandaniyal I agree with @tmmurali  that initiating a fork via `POST graph` API is not a good idea. Infact, I wouldnt want to allow users to set the `parent_id` field using `POST\UPDATE graph` api.

Using a new ENDPOINT will be the right solution here. However, so far none of our API endpoints use verbs. Refer to [RESTful API Designing guidelines](https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9). 

Here is how Github has exposed [create fork](https://developer.github.com/v3/repos/forks/#create-a-fork) api. One change required will be to add a table to store graph-fork relationships.

**Comment by jahandaniyal** [comment]
Closing this issue as this should not be taken up by GSoC '19 prospective students.
