### ISSUE TITLE
Error on uploading Graph

### ISSUE THREAD

**Issue by jajodiaraghav** [Murali-group/GraphSpace#369]
I get the following error on trying to upload a new graph
![capture](https://user-images.githubusercontent.com/18749480/36646050-431a7fd6-1a98-11e8-9c71-c6174de76209.PNG)

**Comment by tmmurali** [comment]
Are you logged in or posting anonymously (i.e., as a public user)?

**Comment by jajodiaraghav** [comment]
I am logging in as a new user. Strangely, None of the first 3 users mentioned in readme file exists. Also, There are no graphs present in my local instance.

**Comment by adbharadwaj** [comment]
@jajodiaraghav Please refer to the following [closed issue](https://github.com/Murali-group/GraphSpace/issues/335). You have not install elasticsearch. Local installations will not have any data (users or graphs). It is also documented [here](https://github.com/Murali-group/GraphSpace/wiki/Common-installation-roadblocks-faced-by-new-contributors). 

Also, here are few things to keep in mind while creating issues in future:
- Kindly, provide more detailed issue title. I would name this issue as **Error: ConnectError(<urllib3.connection.HTTPConnectoin object ...) while uploading graph**
- Refer to both open and closed issues before creating an issue. Although I understand that this issue wouldnt have been searchable because of lack of descriptive issue titles in the past. Hence the first suggestion. Thanks.

I am closing this issue since it has been taken care of.

**Comment by adbharadwaj** [comment]
Also renaming the issue for future search purpose.
